export MANAGEMENT_IF=vio2
export SKIP_IF=vio2
export NETLINK_LINE=4
export LINUX_IF=enp7s0
export LINUX_LEFT_SSH=root@lt90
export LINUX_RIGHT_SSH=root@lt95

export REGRESS_FAIL_EARLY=no
export TEST_SSH_UNSAFE_PERMISSIONS=yes

LOCAL_IF=vio1
LOCAL_MAC=52:54:00:6d:8b:64

export LOCAL_IF LOCAL_MAC
