export MANAGEMENT_IF=vio2
export SKIP_IF=vio2
export NETLINK_LINE=0
export LINUX_IF=enp8s0
export LINUX_LEFT_SSH=root@lt80
export LINUX_RIGHT_SSH=root@lt85

export REGRESS_FAIL_EARLY=no
export TEST_SSH_UNSAFE_PERMISSIONS=yes

LOCAL_IF=vio1
LOCAL_MAC=52:54:00:08:36:74

export LOCAL_IF LOCAL_MAC
