export MANAGEMENT_IF=vio2
export SKIP_IF=vio2
export NETLINK_LINE=5
export LINUX_IF=enp7s0
export LINUX_LEFT_SSH=root@lt49
export LINUX_RIGHT_SSH=root@lt59

export REGRESS_FAIL_EARLY=no
export TEST_SSH_UNSAFE_PERMISSIONS=yes

LOCAL_IF=vio1
LOCAL_MAC=52:54:00:00:9c:58

export LOCAL_IF LOCAL_MAC
