export MANAGEMENT_IF=em4
export NETLINK_LINE=2

# allow to manually run perform tests frag and splice on netlink hosts

LOCAL_ADDR=undef
LOCAL_ADDR6=undef
REMOTE_ADDR=undef
REMOTE_ADDR6=undef
REMOTE_SSH=undef
export LOCAL_ADDR LOCAL_ADDR6 REMOTE_ADDR REMOTE_ADDR6 REMOTE_SSH

LOCAL_ADDR_RANGE=10.10.21.20
LOCAL_ADDR6_RANGE=fdd7:e83e:66bd:1021::20
LINUX_ADDR_RANGE=10.10.22.40
LINUX_ADDR6_RANGE=fdd7:e83e:66bd:1022::40
LINUX_SSH=root@lt40
LINUX_OTHER_SSH=root@lt43
export LOCAL_ADDR_RANGE LOCAL_ADDR6_RANGE LINUX_ADDR_RANGE LINUX_ADDR6_RANGE
export LINUX_SSH LINUX_OTHER_SSH
