name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install packages
      run: |
        sudo apt-get install --yes make perl-base
        sudo apt-get install --yes \
          libdatetime-format-dateparse-perl \
          libhtml-parser-perl
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Make syntax check
      run: make
